name: ai-resume-builder
region: sfo
services:
  - name: frontend
    instance_size_slug: basic-xxs
    instance_count: 1
    git:
      branch: main
      repo_clone_url: https://github.com/minaxixi/AI-Resume-Builder.git
    source_dir: frontend
    build_command: npm install && CI=false npm run build
    run_command: npm run serve -- -l $PORT
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${_self.BACKEND_URL}
      - key: NODE_OPTIONS
        scope: BUILD_TIME
        value: "--max_old_space_size=512"
      - key: NODE_ENV
        scope: RUN_TIME
        value: production

  - name: backend
    instance_size_slug: basic-xxs
    instance_count: 1
    git:
      branch: main
      repo_clone_url: https://github.com/minaxixi/AI-Resume-Builder.git
    source_dir: backend
    run_command: gunicorn --config gunicorn_config.py app:app --bind 0.0.0.0:8080 --log-level debug
    envs:
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${_self.PUBLIC_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"
