name: ai-resume-builder
services:
  - name: backend
    dockerfile_path: Dockerfile.backend
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

  - name: frontend
    dockerfile_path: Dockerfile.frontend
    source_dir: frontend
    github:
      branch: main
      deploy_on_push: true
    routes:
      - path: /
