name: ai-resume-builder
services:
  - name: backend
    environment_slug: python
    source_dir: backend
    run_command: gunicorn app:app --bind 0.0.0.0:$PORT
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

  - name: frontend
    environment_slug: node-js
    source_dir: frontend
    build_command: npm install && npm run build
    run_command: npx serve -s build -l $PORT
