name: ai-resume-builder
services:
  - name: backend
    git:
      branch: main
      repo_clone_url: https://github.com/minaxixi/AI-Resume-Builder.git
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 5001
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_API_KEY}

  - name: frontend
    git:
      branch: main
      repo_clone_url: https://github.com/minaxixi/AI-Resume-Builder.git
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}
